# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift_MVVM_Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift_MVVM_Practice
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'Alamofire'
end
